version: '3'
services:

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: database
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa55w0rd2019"
    ports:
      - "1433:1433"

  controle-presenca-api:
    image: marisouzas2/controlepresenca:latest
    container_name: controle-presenca-api
    ports:
      - "6000:80"
    depends_on:
      - database
    environment:
      - "ConnectionStrings__ControlePresencaDataBase=Server=database,1433;Database=controlepresenca-db;trusted_connection=false;User Id=sa;Password=Pa55w0rd2019;Persist Security Info=False;Encrypt=False"
      - "ASPNETCORE_ENVIRONMENT=Development"